### PR TITLE
Add catch-all route to fix redirect bug

### PR DESCRIPTION
**Pull request by tylerdurrett**
Whenever someone tries to load a page that doesn't have a matching route, they get a console error `Error: Cannot match any routes.` along with a blank screen. This fixes that issue by redirecting to the homepage.

### CODE REVIEW

**Comment by tylerdurrett** [comment]
Hold the bus - this is causing an issue with the sitemap. I'll create a new PR when I get it fixed.

**Comment by tylerdurrett** [comment]
It was working after all. I needed to restart my local server.

**Comment by brianjfox** [comment]
Shouldn't this redirect to a 404 page?  You know, something clever.

**Comment by tylerdurrett** [comment]
I'm totally open to that. I wanted to quickly fix the current broken behavior, but we can also put together a 404 page.

**Comment by tylerdurrett** [comment]
Would it be possible to get this merged? There's still some discussion that needs to happen around 404 page design, and this fix will at least prevent our users from landing on a blank page.

**Pull request merged**
